// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mcast.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinReq struct {
	Hierarchy            int32    `protobuf:"varint,1,opt,name=hierarchy,proto3" json:"hierarchy,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReq) Reset()         { *m = JoinReq{} }
func (m *JoinReq) String() string { return proto.CompactTextString(m) }
func (*JoinReq) ProtoMessage()    {}
func (*JoinReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{0}
}

func (m *JoinReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReq.Unmarshal(m, b)
}
func (m *JoinReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReq.Marshal(b, m, deterministic)
}
func (m *JoinReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReq.Merge(m, src)
}
func (m *JoinReq) XXX_Size() int {
	return xxx_messageInfo_JoinReq.Size(m)
}
func (m *JoinReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReq proto.InternalMessageInfo

func (m *JoinReq) GetHierarchy() int32 {
	if m != nil {
		return m.Hierarchy
	}
	return 0
}

func (m *JoinReq) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type JoinResp struct {
	Hierarchy            int32          `protobuf:"varint,1,opt,name=hierarchy,proto3" json:"hierarchy,omitempty"`
	RttMs                int64          `protobuf:"varint,2,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`
	Time                 int64          `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Self                 *FingerEntry   `protobuf:"bytes,4,opt,name=self,proto3" json:"self,omitempty"`
	FEList               []*FingerEntry `protobuf:"bytes,5,rep,name=FEList,json=fEList,proto3" json:"FEList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JoinResp) Reset()         { *m = JoinResp{} }
func (m *JoinResp) String() string { return proto.CompactTextString(m) }
func (*JoinResp) ProtoMessage()    {}
func (*JoinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{1}
}

func (m *JoinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResp.Unmarshal(m, b)
}
func (m *JoinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResp.Marshal(b, m, deterministic)
}
func (m *JoinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResp.Merge(m, src)
}
func (m *JoinResp) XXX_Size() int {
	return xxx_messageInfo_JoinResp.Size(m)
}
func (m *JoinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResp proto.InternalMessageInfo

func (m *JoinResp) GetHierarchy() int32 {
	if m != nil {
		return m.Hierarchy
	}
	return 0
}

func (m *JoinResp) GetRttMs() int64 {
	if m != nil {
		return m.RttMs
	}
	return 0
}

func (m *JoinResp) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *JoinResp) GetSelf() *FingerEntry {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *JoinResp) GetFEList() []*FingerEntry {
	if m != nil {
		return m.FEList
	}
	return nil
}

type NodeId struct {
	A                    uint64   `protobuf:"varint,1,opt,name=A,json=a,proto3" json:"A,omitempty"`
	B                    uint64   `protobuf:"varint,2,opt,name=B,json=b,proto3" json:"B,omitempty"`
	C                    uint64   `protobuf:"varint,3,opt,name=C,json=c,proto3" json:"C,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeId) Reset()         { *m = NodeId{} }
func (m *NodeId) String() string { return proto.CompactTextString(m) }
func (*NodeId) ProtoMessage()    {}
func (*NodeId) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{2}
}

func (m *NodeId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeId.Unmarshal(m, b)
}
func (m *NodeId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeId.Marshal(b, m, deterministic)
}
func (m *NodeId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeId.Merge(m, src)
}
func (m *NodeId) XXX_Size() int {
	return xxx_messageInfo_NodeId.Size(m)
}
func (m *NodeId) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeId.DiscardUnknown(m)
}

var xxx_messageInfo_NodeId proto.InternalMessageInfo

func (m *NodeId) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *NodeId) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *NodeId) GetC() uint64 {
	if m != nil {
		return m.C
	}
	return 0
}

type FingerEntry struct {
	Id *NodeId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	//fixed64 address = 2;	// for now just the IPv4 address //TODO remove
	Hostname             string   `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FingerEntry) Reset()         { *m = FingerEntry{} }
func (m *FingerEntry) String() string { return proto.CompactTextString(m) }
func (*FingerEntry) ProtoMessage()    {}
func (*FingerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{3}
}

func (m *FingerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FingerEntry.Unmarshal(m, b)
}
func (m *FingerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FingerEntry.Marshal(b, m, deterministic)
}
func (m *FingerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FingerEntry.Merge(m, src)
}
func (m *FingerEntry) XXX_Size() int {
	return xxx_messageInfo_FingerEntry.Size(m)
}
func (m *FingerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FingerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FingerEntry proto.InternalMessageInfo

func (m *FingerEntry) GetId() *NodeId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FingerEntry) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type EvalInfo struct {
	Hops                 int32    `protobuf:"varint,1,opt,name=hops,proto3" json:"hops,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Node                 *NodeId  `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EvalInfo) Reset()         { *m = EvalInfo{} }
func (m *EvalInfo) String() string { return proto.CompactTextString(m) }
func (*EvalInfo) ProtoMessage()    {}
func (*EvalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{4}
}

func (m *EvalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvalInfo.Unmarshal(m, b)
}
func (m *EvalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvalInfo.Marshal(b, m, deterministic)
}
func (m *EvalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvalInfo.Merge(m, src)
}
func (m *EvalInfo) XXX_Size() int {
	return xxx_messageInfo_EvalInfo.Size(m)
}
func (m *EvalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EvalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EvalInfo proto.InternalMessageInfo

func (m *EvalInfo) GetHops() int32 {
	if m != nil {
		return m.Hops
	}
	return 0
}

func (m *EvalInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *EvalInfo) GetNode() *NodeId {
	if m != nil {
		return m.Node
	}
	return nil
}

type FwdPacket struct {
	Limit                *NodeId     `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
	EvalList             []*EvalInfo `protobuf:"bytes,2,rep,name=evalList,proto3" json:"evalList,omitempty"`
	Payload              []byte      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Src                  *NodeId     `protobuf:"bytes,4,opt,name=src,proto3" json:"src,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FwdPacket) Reset()         { *m = FwdPacket{} }
func (m *FwdPacket) String() string { return proto.CompactTextString(m) }
func (*FwdPacket) ProtoMessage()    {}
func (*FwdPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{5}
}

func (m *FwdPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FwdPacket.Unmarshal(m, b)
}
func (m *FwdPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FwdPacket.Marshal(b, m, deterministic)
}
func (m *FwdPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FwdPacket.Merge(m, src)
}
func (m *FwdPacket) XXX_Size() int {
	return xxx_messageInfo_FwdPacket.Size(m)
}
func (m *FwdPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_FwdPacket.DiscardUnknown(m)
}

var xxx_messageInfo_FwdPacket proto.InternalMessageInfo

func (m *FwdPacket) GetLimit() *NodeId {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *FwdPacket) GetEvalList() []*EvalInfo {
	if m != nil {
		return m.EvalList
	}
	return nil
}

func (m *FwdPacket) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FwdPacket) GetSrc() *NodeId {
	if m != nil {
		return m.Src
	}
	return nil
}

type GetFERequest struct {
	Hierarchy            int32    `protobuf:"varint,1,opt,name=hierarchy,proto3" json:"hierarchy,omitempty"`
	Limit                *NodeId  `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFERequest) Reset()         { *m = GetFERequest{} }
func (m *GetFERequest) String() string { return proto.CompactTextString(m) }
func (*GetFERequest) ProtoMessage()    {}
func (*GetFERequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{6}
}

func (m *GetFERequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFERequest.Unmarshal(m, b)
}
func (m *GetFERequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFERequest.Marshal(b, m, deterministic)
}
func (m *GetFERequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFERequest.Merge(m, src)
}
func (m *GetFERequest) XXX_Size() int {
	return xxx_messageInfo_GetFERequest.Size(m)
}
func (m *GetFERequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFERequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFERequest proto.InternalMessageInfo

func (m *GetFERequest) GetHierarchy() int32 {
	if m != nil {
		return m.Hierarchy
	}
	return 0
}

func (m *GetFERequest) GetLimit() *NodeId {
	if m != nil {
		return m.Limit
	}
	return nil
}

type GetFEResponse struct {
	Hierarchy            int32        `protobuf:"varint,1,opt,name=hierarchy,proto3" json:"hierarchy,omitempty"`
	Limit                *NodeId      `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	NewFE                *FingerEntry `protobuf:"bytes,2,opt,name=newFE,proto3" json:"newFE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetFEResponse) Reset()         { *m = GetFEResponse{} }
func (m *GetFEResponse) String() string { return proto.CompactTextString(m) }
func (*GetFEResponse) ProtoMessage()    {}
func (*GetFEResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{7}
}

func (m *GetFEResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFEResponse.Unmarshal(m, b)
}
func (m *GetFEResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFEResponse.Marshal(b, m, deterministic)
}
func (m *GetFEResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFEResponse.Merge(m, src)
}
func (m *GetFEResponse) XXX_Size() int {
	return xxx_messageInfo_GetFEResponse.Size(m)
}
func (m *GetFEResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFEResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetFEResponse proto.InternalMessageInfo

func (m *GetFEResponse) GetHierarchy() int32 {
	if m != nil {
		return m.Hierarchy
	}
	return 0
}

func (m *GetFEResponse) GetLimit() *NodeId {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *GetFEResponse) GetNewFE() *FingerEntry {
	if m != nil {
		return m.NewFE
	}
	return nil
}

type Successor struct {
	FE                   *FingerEntry `protobuf:"bytes,1,opt,name=FE,json=fE,proto3" json:"FE,omitempty"`
	Limit                *NodeId      `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Successor) Reset()         { *m = Successor{} }
func (m *Successor) String() string { return proto.CompactTextString(m) }
func (*Successor) ProtoMessage()    {}
func (*Successor) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{8}
}

func (m *Successor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Successor.Unmarshal(m, b)
}
func (m *Successor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Successor.Marshal(b, m, deterministic)
}
func (m *Successor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Successor.Merge(m, src)
}
func (m *Successor) XXX_Size() int {
	return xxx_messageInfo_Successor.Size(m)
}
func (m *Successor) XXX_DiscardUnknown() {
	xxx_messageInfo_Successor.DiscardUnknown(m)
}

var xxx_messageInfo_Successor proto.InternalMessageInfo

func (m *Successor) GetFE() *FingerEntry {
	if m != nil {
		return m.FE
	}
	return nil
}

func (m *Successor) GetLimit() *NodeId {
	if m != nil {
		return m.Limit
	}
	return nil
}

type H struct {
	H                    int32    `protobuf:"varint,1,opt,name=H,json=h,proto3" json:"H,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *H) Reset()         { *m = H{} }
func (m *H) String() string { return proto.CompactTextString(m) }
func (*H) ProtoMessage()    {}
func (*H) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{9}
}

func (m *H) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_H.Unmarshal(m, b)
}
func (m *H) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_H.Marshal(b, m, deterministic)
}
func (m *H) XXX_Merge(src proto.Message) {
	xxx_messageInfo_H.Merge(m, src)
}
func (m *H) XXX_Size() int {
	return xxx_messageInfo_H.Size(m)
}
func (m *H) XXX_DiscardUnknown() {
	xxx_messageInfo_H.DiscardUnknown(m)
}

var xxx_messageInfo_H proto.InternalMessageInfo

func (m *H) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type IDandH struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	H                    int32    `protobuf:"varint,2,opt,name=H,json=h,proto3" json:"H,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDandH) Reset()         { *m = IDandH{} }
func (m *IDandH) String() string { return proto.CompactTextString(m) }
func (*IDandH) ProtoMessage()    {}
func (*IDandH) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{10}
}

func (m *IDandH) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDandH.Unmarshal(m, b)
}
func (m *IDandH) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDandH.Marshal(b, m, deterministic)
}
func (m *IDandH) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDandH.Merge(m, src)
}
func (m *IDandH) XXX_Size() int {
	return xxx_messageInfo_IDandH.Size(m)
}
func (m *IDandH) XXX_DiscardUnknown() {
	xxx_messageInfo_IDandH.DiscardUnknown(m)
}

var xxx_messageInfo_IDandH proto.InternalMessageInfo

func (m *IDandH) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *IDandH) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a4197c673499c8, []int{11}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JoinReq)(nil), "main.JoinReq")
	proto.RegisterType((*JoinResp)(nil), "main.JoinResp")
	proto.RegisterType((*NodeId)(nil), "main.NodeId")
	proto.RegisterType((*FingerEntry)(nil), "main.FingerEntry")
	proto.RegisterType((*EvalInfo)(nil), "main.EvalInfo")
	proto.RegisterType((*FwdPacket)(nil), "main.FwdPacket")
	proto.RegisterType((*GetFERequest)(nil), "main.GetFERequest")
	proto.RegisterType((*GetFEResponse)(nil), "main.GetFEResponse")
	proto.RegisterType((*Successor)(nil), "main.Successor")
	proto.RegisterType((*H)(nil), "main.H")
	proto.RegisterType((*IDandH)(nil), "main.IDandH")
	proto.RegisterType((*Empty)(nil), "main.Empty")
}

func init() { proto.RegisterFile("mcast.proto", fileDescriptor_17a4197c673499c8) }

var fileDescriptor_17a4197c673499c8 = []byte{
	// 595 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0xd2, 0xf4, 0xef, 0xb4, 0x2b, 0xda, 0x41, 0x48, 0x55, 0x35, 0xa1, 0x62, 0x69, 0x6c,
	0x20, 0xd4, 0x8b, 0x72, 0x39, 0x71, 0x01, 0x5b, 0xb2, 0x16, 0x01, 0x9a, 0x3c, 0xee, 0x51, 0x96,
	0xb8, 0xab, 0x45, 0x6b, 0x67, 0xb1, 0xb7, 0xa9, 0xbc, 0x07, 0x8f, 0xc0, 0x13, 0xf0, 0x82, 0x28,
	0xb6, 0xfb, 0xb3, 0x91, 0x69, 0xbb, 0xcb, 0xf1, 0x39, 0xe7, 0x3b, 0x9f, 0x3f, 0x7f, 0x27, 0xd0,
	0x5e, 0x24, 0xb1, 0xd2, 0xc3, 0x2c, 0x97, 0x5a, 0x62, 0xb0, 0x88, 0xb9, 0x20, 0x47, 0xd0, 0xf8,
	0x2c, 0xb9, 0xa0, 0xec, 0x0a, 0xf7, 0xa0, 0x35, 0xe3, 0x2c, 0x8f, 0xf3, 0x64, 0xb6, 0xec, 0x79,
	0x03, 0xef, 0xb0, 0x46, 0x37, 0x07, 0x88, 0x10, 0x68, 0xbe, 0x60, 0x3d, 0x7f, 0xe0, 0x1d, 0x56,
	0xa9, 0xf9, 0x26, 0x7f, 0x3c, 0x68, 0xda, 0x6e, 0x95, 0x3d, 0xd2, 0xfe, 0x02, 0xea, 0xb9, 0xd6,
	0x3f, 0x16, 0xca, 0x01, 0xd4, 0x72, 0xad, 0xbf, 0xaa, 0x35, 0x6a, 0x75, 0x83, 0x8a, 0xfb, 0x10,
	0x28, 0x36, 0x9f, 0xf6, 0x82, 0x81, 0x77, 0xd8, 0x1e, 0xed, 0x0e, 0x0b, 0x9e, 0xc3, 0x88, 0x8b,
	0x4b, 0x96, 0x87, 0x42, 0xe7, 0x4b, 0x6a, 0xd2, 0xf8, 0x06, 0xea, 0x51, 0xf8, 0x85, 0x2b, 0xdd,
	0xab, 0x0d, 0xaa, 0xe5, 0x85, 0xf5, 0xa9, 0x29, 0x20, 0x23, 0xa8, 0x7f, 0x93, 0x29, 0x9b, 0xa4,
	0xd8, 0x01, 0xef, 0xa3, 0x21, 0x17, 0x50, 0x2f, 0x2e, 0xa2, 0x4f, 0x86, 0x4f, 0x40, 0xbd, 0x8b,
	0x22, 0x3a, 0x36, 0x44, 0x02, 0xea, 0x25, 0xe4, 0x14, 0xda, 0x5b, 0x50, 0xb8, 0x07, 0x3e, 0x4f,
	0x4d, 0x67, 0x7b, 0xd4, 0xb1, 0x93, 0x2c, 0x24, 0xf5, 0x79, 0x8a, 0x7d, 0x68, 0xce, 0xa4, 0xd2,
	0x22, 0x76, 0x57, 0x69, 0xd1, 0x75, 0x4c, 0xbe, 0x43, 0x33, 0xbc, 0x89, 0xe7, 0x13, 0x31, 0x95,
	0xc5, 0x75, 0x67, 0x32, 0x53, 0x4e, 0x1e, 0xf3, 0x5d, 0x26, 0x2c, 0x0e, 0x20, 0x10, 0x32, 0xb5,
	0x58, 0xf7, 0xe7, 0x99, 0x0c, 0xf9, 0xed, 0x41, 0x2b, 0xba, 0x4d, 0xcf, 0xe2, 0xe4, 0x27, 0xd3,
	0x48, 0xa0, 0x36, 0xe7, 0x0b, 0xae, 0x4b, 0x09, 0xda, 0x14, 0xbe, 0x85, 0x26, 0xbb, 0x89, 0xe7,
	0x46, 0x31, 0xdf, 0x28, 0xd6, 0xb5, 0x65, 0x2b, 0x76, 0x74, 0x9d, 0xc7, 0x1e, 0x34, 0xb2, 0x78,
	0x39, 0x97, 0x71, 0x6a, 0x28, 0x74, 0xe8, 0x2a, 0xc4, 0x97, 0x50, 0x55, 0x79, 0xe2, 0xde, 0xe6,
	0xee, 0x9c, 0x22, 0x41, 0xce, 0xa0, 0x73, 0xca, 0x74, 0x14, 0x52, 0x76, 0x75, 0xcd, 0x94, 0x7e,
	0xc4, 0x15, 0x6b, 0xde, 0xfe, 0x83, 0xbc, 0xc9, 0x2f, 0xd8, 0x71, 0x88, 0x2a, 0x93, 0x42, 0xb1,
	0xa7, 0x42, 0x56, 0x1f, 0x96, 0xe2, 0x00, 0x6a, 0x82, 0xdd, 0x46, 0xa1, 0x1b, 0x5b, 0xe2, 0x1c,
	0x9b, 0x27, 0x14, 0x5a, 0xe7, 0xd7, 0x49, 0xc2, 0x94, 0x92, 0x39, 0xbe, 0x02, 0x3f, 0x0a, 0x9d,
	0xc2, 0x25, 0x2d, 0xfe, 0x34, 0x7c, 0xd2, 0x7d, 0x76, 0xc1, 0x1b, 0x17, 0x5e, 0x1b, 0x3b, 0xee,
	0xde, 0x8c, 0xbc, 0x86, 0xfa, 0xe4, 0x24, 0x16, 0xe9, 0x18, 0xbb, 0xe0, 0x4f, 0x4e, 0x9c, 0x41,
	0x7d, 0x7e, 0x62, 0xeb, 0xfc, 0x55, 0x5d, 0x03, 0x6a, 0xe1, 0x22, 0xd3, 0xcb, 0xd1, 0x5f, 0x1f,
	0x1a, 0x66, 0x97, 0x59, 0x8e, 0x07, 0x10, 0x14, 0x3b, 0x88, 0x3b, 0x76, 0x98, 0xdb, 0xe6, 0x7e,
	0x77, 0x3b, 0x54, 0x19, 0xa9, 0xe0, 0x3e, 0x54, 0xa3, 0xdb, 0x14, 0x9f, 0x39, 0xea, 0x2b, 0xf3,
	0xf4, 0xdb, 0xce, 0x06, 0x05, 0x32, 0xa9, 0xe0, 0x11, 0x74, 0x0b, 0xbd, 0xb7, 0xbc, 0x8f, 0xb6,
	0x60, 0xfb, 0x5d, 0xfb, 0xcf, 0xef, 0x9c, 0xd9, 0x97, 0x21, 0x15, 0x1c, 0x42, 0xe7, 0x9c, 0xe9,
	0x8d, 0x66, 0x6e, 0xd8, 0xfa, 0xe0, 0xfe, 0xb0, 0x77, 0xd0, 0xb9, 0xdc, 0xae, 0x6f, 0xd8, 0xf4,
	0xb8, 0xff, 0xbf, 0xc0, 0xa4, 0x82, 0x1f, 0xa0, 0x37, 0xe5, 0x22, 0x3d, 0x9e, 0x4b, 0xc5, 0x94,
	0x3e, 0xcb, 0x59, 0xc2, 0x52, 0x2e, 0x2e, 0x0b, 0x7d, 0xd1, 0x69, 0x6d, 0x75, 0x2c, 0x6d, 0xbf,
	0xa8, 0x9b, 0x1f, 0xdf, 0xfb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x38, 0x88, 0x4a, 0x07,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// McasterClient is the client API for Mcaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type McasterClient interface {
	Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinResp, error)
	Fwd(ctx context.Context, in *FwdPacket, opts ...grpc.CallOption) (*Empty, error)
	GetFingerEntry(ctx context.Context, in *GetFERequest, opts ...grpc.CallOption) (*GetFEResponse, error)
	SetSuccessor(ctx context.Context, in *Successor, opts ...grpc.CallOption) (*Empty, error)
	GetSuccessor(ctx context.Context, in *H, opts ...grpc.CallOption) (*FingerEntry, error)
	FindClosestPrecedingNode(ctx context.Context, in *IDandH, opts ...grpc.CallOption) (*FingerEntry, error)
}

type mcasterClient struct {
	cc grpc.ClientConnInterface
}

func NewMcasterClient(cc grpc.ClientConnInterface) McasterClient {
	return &mcasterClient{cc}
}

func (c *mcasterClient) Join(ctx context.Context, in *JoinReq, opts ...grpc.CallOption) (*JoinResp, error) {
	out := new(JoinResp)
	err := c.cc.Invoke(ctx, "/main.mcaster/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcasterClient) Fwd(ctx context.Context, in *FwdPacket, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/main.mcaster/Fwd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcasterClient) GetFingerEntry(ctx context.Context, in *GetFERequest, opts ...grpc.CallOption) (*GetFEResponse, error) {
	out := new(GetFEResponse)
	err := c.cc.Invoke(ctx, "/main.mcaster/GetFingerEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcasterClient) SetSuccessor(ctx context.Context, in *Successor, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/main.mcaster/SetSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcasterClient) GetSuccessor(ctx context.Context, in *H, opts ...grpc.CallOption) (*FingerEntry, error) {
	out := new(FingerEntry)
	err := c.cc.Invoke(ctx, "/main.mcaster/getSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcasterClient) FindClosestPrecedingNode(ctx context.Context, in *IDandH, opts ...grpc.CallOption) (*FingerEntry, error) {
	out := new(FingerEntry)
	err := c.cc.Invoke(ctx, "/main.mcaster/findClosestPrecedingNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McasterServer is the server API for Mcaster service.
type McasterServer interface {
	Join(context.Context, *JoinReq) (*JoinResp, error)
	Fwd(context.Context, *FwdPacket) (*Empty, error)
	GetFingerEntry(context.Context, *GetFERequest) (*GetFEResponse, error)
	SetSuccessor(context.Context, *Successor) (*Empty, error)
	GetSuccessor(context.Context, *H) (*FingerEntry, error)
	FindClosestPrecedingNode(context.Context, *IDandH) (*FingerEntry, error)
}

// UnimplementedMcasterServer can be embedded to have forward compatible implementations.
type UnimplementedMcasterServer struct {
}

func (*UnimplementedMcasterServer) Join(ctx context.Context, req *JoinReq) (*JoinResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedMcasterServer) Fwd(ctx context.Context, req *FwdPacket) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fwd not implemented")
}
func (*UnimplementedMcasterServer) GetFingerEntry(ctx context.Context, req *GetFERequest) (*GetFEResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFingerEntry not implemented")
}
func (*UnimplementedMcasterServer) SetSuccessor(ctx context.Context, req *Successor) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSuccessor not implemented")
}
func (*UnimplementedMcasterServer) GetSuccessor(ctx context.Context, req *H) (*FingerEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuccessor not implemented")
}
func (*UnimplementedMcasterServer) FindClosestPrecedingNode(ctx context.Context, req *IDandH) (*FingerEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindClosestPrecedingNode not implemented")
}

func RegisterMcasterServer(s *grpc.Server, srv McasterServer) {
	s.RegisterService(&_Mcaster_serviceDesc, srv)
}

func _Mcaster_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McasterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.mcaster/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McasterServer).Join(ctx, req.(*JoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcaster_Fwd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FwdPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McasterServer).Fwd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.mcaster/Fwd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McasterServer).Fwd(ctx, req.(*FwdPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcaster_GetFingerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McasterServer).GetFingerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.mcaster/GetFingerEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McasterServer).GetFingerEntry(ctx, req.(*GetFERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcaster_SetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Successor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McasterServer).SetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.mcaster/SetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McasterServer).SetSuccessor(ctx, req.(*Successor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcaster_GetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(H)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McasterServer).GetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.mcaster/GetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McasterServer).GetSuccessor(ctx, req.(*H))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcaster_FindClosestPrecedingNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDandH)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McasterServer).FindClosestPrecedingNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.mcaster/FindClosestPrecedingNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McasterServer).FindClosestPrecedingNode(ctx, req.(*IDandH))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mcaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.mcaster",
	HandlerType: (*McasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Mcaster_Join_Handler,
		},
		{
			MethodName: "Fwd",
			Handler:    _Mcaster_Fwd_Handler,
		},
		{
			MethodName: "GetFingerEntry",
			Handler:    _Mcaster_GetFingerEntry_Handler,
		},
		{
			MethodName: "SetSuccessor",
			Handler:    _Mcaster_SetSuccessor_Handler,
		},
		{
			MethodName: "getSuccessor",
			Handler:    _Mcaster_GetSuccessor_Handler,
		},
		{
			MethodName: "findClosestPrecedingNode",
			Handler:    _Mcaster_FindClosestPrecedingNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcast.proto",
}
